import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import { AuthInit } from "@/components/Auth/AuthProvider";

const montserrat = Montserrat({
    variable: "--font-geist-montserrat",
    subsets: ["latin", "cyrillic"],
});

const inter = Inter({
    variable: "--font-geist-inter",
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${montserrat.variable} ${inter.variable} antialiased`}
            >
                <NavBar />
                <main className="container font-sans mx-auto mt-20 min-h-[calc(100vh-60px)] h-fit">
                    {children}
                </main>
                <footer className="h-20 bg-black/25 mt-5"></footer>
                <AuthInit />
            </body>
        </html>
    );
}
